type Product {
  id: ID
  title: String
  text: String
  price: Int
  thumbnail: String
}

type Cart {
  id: ID!
  products: [Product]
}

type Query {
    bringsAllCarts: [Cart]
    bringsCartById(id: ID!): Cart
}


type Mutation {
    createCart: [Cart]
    deleteCart(id:ID!): [Cart]
    AddProductToCart(id:ID!, idProduct: ID!): Cart
    deleteProductFromCart(id:ID!, idProduct:ID!): Cart
}
